events { worker_connections 1024; }

http {
    upstream mlflow   { server mlflow:5001; }
    upstream inference { server inference-api:8000; }

    server {
        listen 80;

        location /mlflow/ {
            proxy_pass       http://mlflow/;
            proxy_set_header Host $host;
            proxy_read_timeout 300s;
        }

        location /api/ {
            proxy_pass       http://inference/;
            proxy_set_header Host $host;
        }

        location /nginx-health {
            return 200 "ok\n";
            add_header Content-Type text/plain;
        }
    }
}
